/**
 * capture-slides.mjs
 * Screenshots every slide state from PRESENTATION.html (including step reveals)
 * and writes src/slideList.ts for use in Remotion.
 *
 * Run: node scripts/capture-slides.mjs
 * Output: public/slides/slide-XX-sY.png  and  src/slideList.ts
 */

import puppeteer from "puppeteer";
import { writeFileSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const SLIDES_DIR = resolve(ROOT, "public", "slides");
const PRESENTATION = resolve(ROOT, "..", "PRESENTATION.html");
const SLIDE_LIST_OUT = resolve(ROOT, "src", "slideList.ts");

mkdirSync(SLIDES_DIR, { recursive: true });

const TOTAL_SLIDES = 15;

// Slides that have step-reveal elements (0-indexed)
const STEP_SLIDES = new Set([1, 6, 11]); // s2=idx1, s7=idx6, s12=idx11

async function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

async function main() {
  console.log("Launching browser...");
  const browser = await puppeteer.launch({
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox", "--window-size=1920,1080"],
  });

  const page = await browser.newPage();
  await page.setViewport({ width: 1920, height: 1080 });

  const fileUrl = `file://${PRESENTATION}`;
  console.log(`Opening: ${fileUrl}`);
  await page.goto(fileUrl, { waitUntil: "networkidle0" });
  await sleep(1000); // let initial animations run

  const allImages = []; // { slide: number, step: number, file: string }

  for (let idx = 0; idx < TOTAL_SLIDES; idx++) {
    const slideNum = idx + 1;
    const pad = String(slideNum).padStart(2, "0");

    console.log(`\nSlide ${slideNum}/${TOTAL_SLIDES}...`);

    // Jump directly to slide
    await page.evaluate((i) => {
      // go() is defined in PRESENTATION.html
      if (typeof go === "function") go(i);
    }, idx);
    await sleep(900); // wait for entry animations

    // Screenshot initial state (step 0)
    const s0file = `slide-${pad}-s0.png`;
    await page.screenshot({ path: resolve(SLIDES_DIR, s0file), type: "png" });
    allImages.push({ slide: slideNum, step: 0, file: s0file });
    console.log(`  saved ${s0file}`);

    // If this slide has steps, reveal them one by one
    if (STEP_SLIDES.has(idx)) {
      let stepIdx = 1;
      let hasMore = true;
      while (hasMore) {
        hasMore = await page.evaluate(() => {
          if (typeof advanceStep === "function") return advanceStep();
          return false;
        });
        if (!hasMore) break;
        await sleep(200);
        const sNfile = `slide-${pad}-s${stepIdx}.png`;
        await page.screenshot({ path: resolve(SLIDES_DIR, sNfile), type: "png" });
        allImages.push({ slide: slideNum, step: stepIdx, file: sNfile });
        console.log(`  saved ${sNfile}`);
        stepIdx++;
      }
    }
  }

  await browser.close();
  console.log(`\nCaptured ${allImages.length} images total.`);

  // Build PART1 (slides 1-11, all states) and PART3 (slides 11-15, all states)
  const part1 = allImages.filter((i) => i.slide >= 1 && i.slide <= 11);
  const part3 = allImages.filter((i) => i.slide >= 11 && i.slide <= 15);

  const toStaticLines = (imgs) =>
    imgs.map((i) => `  staticFile('slides/${i.file}'),`).join("\n");

  const ts = `// Auto-generated by scripts/capture-slides.mjs, do not edit manually
import { staticFile } from 'remotion';

export const PART1_SLIDES: string[] = [
${toStaticLines(part1)}
];

export const PART3_SLIDES: string[] = [
${toStaticLines(part3)}
];

export function calcDuration(images: string[], secPerImage: number, fps: number): number {
  return images.length * secPerImage * fps;
}
`;

  writeFileSync(SLIDE_LIST_OUT, ts, "utf8");
  console.log(`Wrote ${SLIDE_LIST_OUT}`);
  console.log(
    `PART1: ${part1.length} images, PART3: ${part3.length} images`
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
