// Auto-generated by scripts/capture-slides.mjs — do not edit manually
import { staticFile } from 'remotion';

export const PART1_SLIDES: string[] = [
  staticFile('slides/slide-01-s0.png'),
  staticFile('slides/slide-02-s0.png'),
  staticFile('slides/slide-02-s1.png'),
  staticFile('slides/slide-02-s2.png'),
  staticFile('slides/slide-02-s3.png'),
  staticFile('slides/slide-02-s4.png'),
  staticFile('slides/slide-02-s5.png'),
  staticFile('slides/slide-03-s0.png'),
  staticFile('slides/slide-04-s0.png'),
  staticFile('slides/slide-05-s0.png'),
  staticFile('slides/slide-06-s0.png'),
  staticFile('slides/slide-07-s0.png'),
  staticFile('slides/slide-07-s1.png'),
  staticFile('slides/slide-07-s2.png'),
  staticFile('slides/slide-07-s3.png'),
  staticFile('slides/slide-08-s0.png'),
  staticFile('slides/slide-09-s0.png'),
  staticFile('slides/slide-10-s0.png'),
  staticFile('slides/slide-11-s0.png'),
];

export const PART3_SLIDES: string[] = [
  staticFile('slides/slide-11-s0.png'),
  staticFile('slides/slide-12-s0.png'),
  staticFile('slides/slide-12-s1.png'),
  staticFile('slides/slide-12-s2.png'),
  staticFile('slides/slide-12-s3.png'),
  staticFile('slides/slide-12-s4.png'),
  staticFile('slides/slide-12-s5.png'),
  staticFile('slides/slide-13-s0.png'),
  staticFile('slides/slide-14-s0.png'),
  staticFile('slides/slide-15-s0.png'),
];

export function calcDuration(images: string[], secPerImage: number, fps: number): number {
  return images.length * secPerImage * fps;
}
